{% set version = "5.4.5" %}

package:
  name: gmt
  version: {{ version }}

source:
  url: https://github.com/GenericMappingTools/gmt/releases/download/{{ version }}/gmt-{{ version }}-src.tar.gz
  sha256: 225629c7869e204d5f9f1a384c4ada43e243f83e1ed28bdca4f7c2896bf39ef6
  patches:
    - no_matlab.patch

build:
  number: 33
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make  # [not win]
  host:
    - libblas
    - libcblas
    - liblapack
    - fftw
    - gdal
    - ghostscript
    - libnetcdf
    - hdf5
    - zlib
    - curl
    - pcre
    - gshhg-gmt
    - dcw-gmt
  run:
    - libblas
    - libcblas
    - liblapack
    - {{ pin_compatible('fftw', max_pin='x') }}
    - {{ pin_compatible('gdal', max_pin='x.x') }}
    - ghostscript
    - libnetcdf
    - hdf5
    - {{ pin_compatible('zlib', max_pin='x.x') }}
    - {{ pin_compatible('curl', max_pin='x') }}
    - pcre
    - gshhg-gmt  # [not win]
    - dcw-gmt  # [not win]

test:
  commands:
    - gmt defaults -Vd  # [not linux]
    - gmt psbasemap -R10/70/-3/8 -JX4i/3i -Ba -B+glightred+t"TEST" -P -Vd > test0.ps  # [not linux]
    - gmt pscoast -R0/10/0/10 -JM6i -Ba -Ggray -ENG+p1p,blue -P -Vd > test1.ps  # [not linux]

about:
  home: https://www.generic-mapping-tools.org
  license: LGPL-3.0-or-later
  license_file: LICENSE.TXT
  summary: 'The Generic Mapping Tools.'
  description: |
      GMT is an open source collection of about 80 command-line tools for
      manipulating geographic and Cartesian data sets (including filtering,
      trend fitting, gridding, projecting, etc.) and producing PostScript
      illustrations ranging from simple x–y plots via contour maps to
      artificially illuminated surfaces and 3D perspective views; the GMT
      supplements add another 40 more specialized and discipline-specific
      tools. GMT supports over 30 map projections and transformations

extra:
  recipe-maintainers:
    - ocefpaf
    - leouieda
    - seisman
