{% set version = "6.0.0a8" %}
{% set variant = "openblas" %}

package:
  name: gmt
  version: {{ version }}

source:
  svn_url: svn://gmtserver.soest.hawaii.edu/gmt/trunk
  svn_rev: 18888

build:
  number: 200
  skip: True  # [win]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - svn
    - cmake
    - fftw
    - gdal 2.2.*
    - ghostscript
    - libnetcdf 4.4.*
    - hdf5 1.8.18|1.8.18.*
    - zlib 1.2.*
    - blas 1.1 {{ variant }}
    - curl
    - pcre
    - openblas 0.2.19|0.2.19.*
    - gshhg-gmt
    - dcw-gmt
  run:
    - fftw
    - gdal 2.2.*
    - ghostscript
    - libnetcdf 4.4.*
    - hdf5 1.8.18|1.8.18.*
    - zlib 1.2.*
    - blas 1.1 {{ variant }}
    - curl
    - pcre
    - openblas 0.2.19|0.2.19.*
    - gshhg-gmt
    - dcw-gmt

test:
  commands:
    - gmt psbasemap -R10/70/-3/8 -JX4i/3i -Ba -B+glightred+t"TEST" -P > test0.ps  # [not win]
    - gmt pscoast -Vd -R0/5/0/5 -JM5i -P -W0.25p > test1.ps  # [not win]
    - gmt pscoast -R-130/-70/24/52 -JB-100/35/33/45/6i -Ba -B+t"Conic Projection" -N1/thickest -N2/thinnest -A500 -Ggray -Wthinnest -P > test2.ps
    - conda inspect linkages -p $PREFIX gmt  # [not win]
    - conda inspect objects -p $PREFIX gmt  # [osx]

about:
  home: http://gmt.soest.hawaii.edu/
  license: LGPL-3.0
  license_file: LICENSE.TXT
  summary: 'The Generic Mapping Tools.'
  description: |
      GMT is an open source collection of about 80 command-line tools for
      manipulating geographic and Cartesian data sets (including filtering,
      trend fitting, gridding, projecting, etc.) and producing PostScript
      illustrations ranging from simple x–y plots via contour maps to
      artificially illuminated surfaces and 3D perspective views; the GMT
      supplements add another 40 more specialized and discipline-specific
      tools. GMT supports over 30 map projections and transformations

extra:
  recipe-maintainers:
    - ocefpaf
    - leouieda
