{% set version = "5.4.5" %}
{% set variant = "openblas" %}

package:
  name: gmt
  version: {{ version }}

source:
  url: ftp://ftp.soest.hawaii.edu/gmt/gmt-{{ version }}-src.tar.gz
  sha256: 225629c7869e204d5f9f1a384c4ada43e243f83e1ed28bdca4f7c2896bf39ef6

build:
  number: 0
  skip: True  # [win]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
  host:
    - fftw
    - gdal
    - ghostscript
    - libnetcdf
    - hdf5
    - zlib
    - blas 1.1 {{ variant }}
    - curl
    - pcre
    - openblas
    - gshhg-gmt
    - dcw-gmt
  run:
    - fftw
    - gdal
    - ghostscript
    - libnetcdf
    - hdf5
    - zlib
    - blas 1.1 {{ variant }}
    - curl
    - pcre
    - openblas
    - gshhg-gmt
    - dcw-gmt

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
    - gmt defaults -Vd
    - gmt psbasemap -R10/70/-3/8 -JX4i/3i -Ba -B+glightred+t"TEST" -P -Vd > test0.ps
    - gmt pscoast -R0/5/0/5 -JM5i -P -W0.25p -Vd > test1.ps

about:
  home: http://gmt.soest.hawaii.edu/
  license: LGPL-3.0
  license_file: LICENSE.TXT
  summary: 'The Generic Mapping Tools.'
  description: |
      GMT is an open source collection of about 80 command-line tools for
      manipulating geographic and Cartesian data sets (including filtering,
      trend fitting, gridding, projecting, etc.) and producing PostScript
      illustrations ranging from simple x–y plots via contour maps to
      artificially illuminated surfaces and 3D perspective views; the GMT
      supplements add another 40 more specialized and discipline-specific
      tools. GMT supports over 30 map projections and transformations

extra:
  recipe-maintainers:
    - ocefpaf
    - leouieda
