{% set version = "5.4.2" %}
{% set variant = "openblas" %}

package:
  name: gmt
  version: {{ version }}

source:
  fn: gmt-{{ version }}-src.tar.gz
  url: ftp://ftp.soest.hawaii.edu/gmt/gmt-{{ version }}-src.tar.gz
  sha256: 288509d28ed062ddf8b08212f65afb3aa07762a9a84bc5da9f7132016c8dd31f

build:
  number: 2
  skip: True  # [win and py36]
  features:
    - blas_{{ variant }}  # [not win]
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - python  # [win]
    - cmake
    - fftw
    - gdal 2.2.*
    - ghostscript  # [not win]
    - libnetcdf 4.4.*
    - hdf5 1.8.18|1.8.18.*
    - zlib 1.2.8
    - blas 1.1 {{ variant }}  # [not win]
    - curl
    - pcre
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and (py35 or py36)]
    - msinttypes  # [win and py<35]
  run:
    - fftw
    - gdal 2.2.*
    - ghostscript  # [not win]
    - libnetcdf 4.4.*
    - hdf5 1.8.18|1.8.18.*
    - zlib 1.2.*
    - blas 1.1 {{ variant }}  # [not win]
    - curl
    - pcre
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and (py35 or py36)]

test:
  commands:
    - gmt psbasemap -R10/70/-3/8 -JX4i/3i -Ba -B+glightred+t"TEST" -P > test0.ps  # [not win]
    - gmt pscoast -Vd -R0/5/0/5 -JM5i -P -W0.25p > test1.ps  # [not win]
    - gmt pscoast -R-130/-70/24/52 -JB-100/35/33/45/6i -Ba -B+t"Conic Projection" -N1/thickest -N2/thinnest -A500 -Ggray -Wthinnest -P > test2.ps
    - conda inspect linkages -p $PREFIX gmt  # [not win]
    - conda inspect objects -p $PREFIX gmt  # [osx]

about:
  home: http://gmt.soest.hawaii.edu/
  license: LGPL-3.0
  license_file: LICENSE.TXT
  summary: 'Generic Mapping Tools.'

extra:
  recipe-maintainers:
    - ocefpaf
    - leouieda
