package:
  name: gmt
  version: 6.6.0.dev5+b3580a7
source:
  git_url: https://github.com/GenericMappingTools/gmt.git
  git_rev: b3580a7a7a575c9bacd4cdfb54214886ca157038
build:
  number: 0
requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make  # [not win]
  host:
    - libblas
    - libcblas
    - liblapack
    - libgdal-core
    - fftw
    - geos
    - glib
    - ghostscript
    - libnetcdf
    - hdf5
    - zlib
    - curl
    - pcre
    - gshhg-gmt
    - dcw-gmt
  run:
    - libblas
    - libcblas
    - liblapack
    - {{ pin_compatible('fftw', max_pin='x') }}
    - {{ pin_compatible('gdal', max_pin='x.x') }}
    - geos
    - ghostscript
    - libgdal-jp2openjpeg
    - libnetcdf
    - hdf5
    - {{ pin_compatible('zlib', max_pin='x.x') }}
    - {{ pin_compatible('curl', max_pin='x') }}
    - pcre
    - gshhg-gmt  # [not win]
    - dcw-gmt  # [not win]
test:
  commands:
    # Test plotting basemap with coastlines
    - gmt defaults -Vd
    - gmt psbasemap -R10/70/-3/8 -JX4i/3i -Ba -B+glightred+t"TEST" -P -Vd > test0.ps
    - gmt pscoast -R0/10/0/10 -JM6i -Ba -Ggray -ENG+p1p,blue -P -Vd > test1.ps
    - gmt begin -Vd
    - gmt coast -R0/10/0/10 -JM6i -Ba -Ggray -ENG+p1p,blue -Vd
    - gmt end
    # Test OpenMP multi-core with -x2
    - gmt-config --all  # [not win]
    - gmt  # [win]
    - gmt grdmath -Rg -I1 0 90 SDIST = dist_to_NP.nc -x2
    # Test reading/writing a JP2 file (S90E000.earth_relief_05m_p.jp2)
    - gmt grdcut @earth_relief_05m -R-10/-9/3/5 -Greliefcut.jp2=gd:JP2OpenJPEG
    - "[ -e 'reliefcut.jp2' ] && exit 0 || exit 1"
about:
  home: https://www.generic-mapping-tools.org
  license: LGPL-3.0-or-later
  license_file: LICENSE.TXT
  summary: 'The Generic Mapping Tools.'
  description: |
    GMT is an open source collection of about 80 command-line tools for
    manipulating geographic and Cartesian data sets (including filtering,
    trend fitting, gridding, projecting, etc.) and producing PostScript
    illustrations ranging from simple x–y plots via contour maps to
    artificially illuminated surfaces and 3D perspective views; the GMT
    supplements add another 40 more specialized and discipline-specific
    tools. GMT supports over 30 map projections and transformations
extra:
  recipe-maintainers:
    - ocefpaf
    - leouieda
    - seisman
