{% set version = "6.6.0" %}

package:
  name: gmt
  version: {{ version }}

source:
  url: https://github.com/GenericMappingTools/gmt/releases/download/{{ version }}/gmt-{{ version }}-src.tar.gz
  sha256: 28c0e56a31d8f3606da18a8e7473eb40647b031df21c69a3e42255953c95bfe4

build:
  number: 1

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make  # [not win]
  host:
    - libblas
    - libcblas
    - liblapack
    - fftw
    - geos
    - glib
    - ghostscript
    - libgdal-core
    - libnetcdf
    - hdf5
    - zlib
    - curl
    - pcre
    - gshhg-gmt
    - dcw-gmt
  run:
    - {{ pin_compatible('fftw', max_pin='x') }}
    - geos
    - ghostscript
    - {{ pin_compatible('libgdal-core', max_pin='x.x') }}
    - libgdal-jp2openjpeg
    - libnetcdf
    - hdf5
    - {{ pin_compatible('zlib', max_pin='x.x') }}
    - {{ pin_compatible('curl', max_pin='x') }}
    - pcre
    - gshhg-gmt  # [not win]
    - dcw-gmt  # [not win]

test:
  commands:
    # Test plotting basemap with coastlines
    - gmt defaults -Vd
    - gmt psbasemap -R10/70/-3/8 -JX4i/3i -Ba -B+glightred+t"TEST" -P -Vd > test0.ps
    - gmt pscoast -R0/10/0/10 -JM6i -Ba -Ggray -ENG+p1p,blue -P -Vd > test1.ps
    - gmt begin -Vd
    - gmt coast -R0/10/0/10 -JM6i -Ba -Ggray -ENG+p1p,blue -Vd
    - gmt end
    # Test OpenMP multi-core with -x2
    - gmt-config --all  # [not win]
    - gmt  # [win]
    - gmt grdmath -Rg -I1 0 90 SDIST = dist_to_NP.nc -x2
    # Test reading/writing a JP2 file (S90E000.earth_relief_05m_p.jp2)
    - gmt grdcut @earth_relief_05m -R-10/-9/3/5 -Greliefcut.jp2=gd:JP2OpenJPEG
    - "[ -e 'reliefcut.jp2' ] && exit 0 || exit 1"

about:
  home: https://www.generic-mapping-tools.org
  doc_url: https://docs.generic-mapping-tools.org
  dev_url: https://github.com/GenericMappingTools/gmt
  license: LGPL-3.0-or-later
  license_file: LICENSE.TXT
  summary: The Generic Mapping Tools.
  description: |
    GMT is an open source collection of about 80 command-line tools for
    manipulating geographic and Cartesian data sets (including filtering,
    trend fitting, gridding, projecting, etc.) and producing PostScript
    illustrations ranging from simple x–y plots via contour maps to
    artificially illuminated surfaces and 3D perspective views; the GMT
    supplements add another 40 more specialized and discipline-specific
    tools. GMT supports over 30 map projections and transformations

extra:
  recipe-maintainers:
    - ocefpaf
    - leouieda
    - seisman
