{% set version = "5.4.2" %}
{% set variant = "openblas" %}

package:
  name: gmt
  version: {{ version }}

source:
  url: ftp://ftp.soest.hawaii.edu/gmt/gmt-{{ version }}-src.tar.gz
  sha256: 288509d28ed062ddf8b08212f65afb3aa07762a9a84bc5da9f7132016c8dd31f

build:
  number: 201
  skip: True  # [win]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - cmake
    - fftw
    - gdal 2.1.*
    - ghostscript
    - libnetcdf 4.4.*
    - hdf5 1.8.18|1.8.18.*
    - zlib 1.2.11
    - blas 1.1 {{ variant }}
    - curl >=7.44.0,<8
    - pcre
    - openblas 0.2.19|0.2.19.*
    - gshhg-gmt
    - dcw-gmt
  run:
    - fftw
    - gdal 2.1.*
    - ghostscript
    - libnetcdf 4.4.*
    - hdf5 1.8.18|1.8.18.*
    - zlib 1.2.11
    - blas 1.1 {{ variant }}
    - curl >=7.44.0,<8
    - pcre
    - openblas 0.2.19|0.2.19.*
    - gshhg-gmt
    - dcw-gmt

test:
  commands:
    - gmt psbasemap -R10/70/-3/8 -JX4i/3i -Ba -B+glightred+t"TEST" -P > test0.ps  # [not win]
    - gmt pscoast -Vd -R0/5/0/5 -JM5i -P -W0.25p > test1.ps  # [not win]
    - gmt pscoast -R-130/-70/24/52 -JB-100/35/33/45/6i -Ba -B+t"Conic Projection" -N1/thickest -N2/thinnest -A500 -Ggray -Wthinnest -P > test2.ps
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://gmt.soest.hawaii.edu/
  license: LGPL-3.0
  license_file: LICENSE.TXT
  summary: 'The Generic Mapping Tools.'
  description: |
      GMT is an open source collection of about 80 command-line tools for
      manipulating geographic and Cartesian data sets (including filtering,
      trend fitting, gridding, projecting, etc.) and producing PostScript
      illustrations ranging from simple x–y plots via contour maps to
      artificially illuminated surfaces and 3D perspective views; the GMT
      supplements add another 40 more specialized and discipline-specific
      tools. GMT supports over 30 map projections and transformations

extra:
  recipe-maintainers:
    - ocefpaf
    - leouieda
