build_platform:
  osx_arm64: osx_64
compiler_stack: comp7
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
max_py_ver: '37'
max_r_ver: '35'
provider:
  linux_aarch64: default
  linux_ppc64le: default
test_on_native_only: true
